### PR TITLE
Fix ARTV

### PR DESCRIPTION
**Pull request by LITUATUI**
New link for ARTV.

### CODE REVIEW

**Comment by marado** [comment]
Hi @LITUATUI ... can you please explain what does this fix? Both links seem to work for me, and stream exactly the same...

**Comment by LITUATUI** [comment]
Hi.

https://5e4fc274d9d46.streamlock.net/livenlin4/2liveartvpub/playlist.m3u8 (original stream not working)
https://playout175.livextend.cloud/livenlin4/2liveartvpub/playlist.m3u8 (new stream working)

**Review by marmelo — APPROVED** [review]

**Comment by marmelo** [comment]
Hi @LITUATUI,

Like @marado said both links are the same.
Also, both domains resolve to the same IP address.

That said, I just checked the https://canal.parlamento.pt/ website and the video stream address is the new one you mention.
This is why I am accepting the pull request.

Thanks!

**Comment by LITUATUI** [comment]
Strange, because in my computer and tvbox the old link doesn't work.

**Pull request merged**
